/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange credentials for a long-lived bearer token
         * @description The only unauthenticated endpoint. No registration exists; the two users are seeded server-side.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deferred-payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List deferred/recurring payment items
         * @description Returns live records only; tombstoned records are excluded. Use /sync/pull to receive tombstones.
         */
        get: operations["list-deferred-payments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deferred-payments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a deferred payment item */
        get: operations["get-deferred-payments"];
        /**
         * Create or replace a deferred payment item
         * @description Clients own record identity: the body carries the client-generated UUID and `updatedAt`.
         */
        put: operations["put-deferred-payments"];
        post?: never;
        /**
         * Delete a deferred payment item (soft delete)
         * @description Sets the `deletedAt` tombstone rather than removing the row, so the deletion propagates to the other device via sync. Idempotent.
         */
        delete: operations["delete-deferred-payments"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/expenses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List expenses
         * @description Returns live records only; tombstoned records are excluded. Use /sync/pull to receive tombstones.
         */
        get: operations["list-expenses"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/expenses/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a expense */
        get: operations["get-expenses"];
        /**
         * Create or replace a expense
         * @description Clients own record identity: the body carries the client-generated UUID and `updatedAt`.
         */
        put: operations["put-expenses"];
        post?: never;
        /**
         * Delete a expense (soft delete)
         * @description Sets the `deletedAt` tombstone rather than removing the row, so the deletion propagates to the other device via sync. Idempotent.
         */
        delete: operations["delete-expenses"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/months": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all month periods
         * @description Returns live records only; tombstoned records are excluded. Use /sync/pull to receive tombstones.
         */
        get: operations["list-months"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/months/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a month */
        get: operations["get-months"];
        /**
         * Create or replace a month
         * @description Clients own record identity: the body carries the client-generated UUID and `updatedAt`.
         */
        put: operations["put-months"];
        post?: never;
        /**
         * Delete a month (soft delete)
         * @description Sets the `deletedAt` tombstone rather than removing the row, so the deletion propagates to the other device via sync. Idempotent. Soft-deletes the month and cascade-tombstones its expenses and tickets.
         */
        delete: operations["delete-months"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sync/pull": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pull all records modified after a given timestamp
         * @description Includes soft-deleted records (with `deletedAt` set) so the client can propagate deletions locally.
         */
        get: operations["sync-pull"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sync/push": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Push locally created or modified records
         * @description Per-record last-write-wins on `updatedAt`: newer records replace stored ones, stale records are skipped. Records with `deletedAt` set apply as deletions under the same rule. Ticket items are replaced wholesale with their parent ticket.
         */
        post: operations["sync-push"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List tickets
         * @description Returns live records only; tombstoned records are excluded. Use /sync/pull to receive tombstones.
         */
        get: operations["list-tickets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a ticket */
        get: operations["get-tickets"];
        /**
         * Create or replace a ticket
         * @description Clients own record identity: the body carries the client-generated UUID and `updatedAt`. Ticket items are replaced wholesale with the parent ticket on every write; items do not sync independently.
         */
        put: operations["put-tickets"];
        post?: never;
        /**
         * Delete a ticket (soft delete)
         * @description Sets the `deletedAt` tombstone rather than removing the row, so the deletion propagates to the other device via sync. Idempotent.
         */
        delete: operations["delete-tickets"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets/{id}/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Transition ticket review state
         * @description Valid transitions: draft → pendingReview, pendingReview → accepted, pendingReview → draft, accepted → draft. The ticket's creator cannot accept their own ticket (422) when `createdByRaw` is known. Accepting does not create expenses server-side; the accepting client materializes expenses and syncs them with `ticketId` set.
         */
        post: operations["transition-ticket-state"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wallet/movements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List wallet movements
         * @description Returns live records only; tombstoned records are excluded. Use /sync/pull to receive tombstones.
         */
        get: operations["list-wallet-movements"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wallet/movements/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a wallet movement */
        get: operations["get-wallet-movements"];
        /**
         * Create or replace a wallet movement
         * @description Clients own record identity: the body carries the client-generated UUID and `updatedAt`.
         */
        put: operations["put-wallet-movements"];
        post?: never;
        /**
         * Delete a wallet movement (soft delete)
         * @description Sets the `deletedAt` tombstone rather than removing the row, so the deletion propagates to the other device via sync. Idempotent.
         */
        delete: operations["delete-wallet-movements"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        DeferredPaymentItem: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/DeferredPaymentItem.json
             */
            readonly $schema?: string;
            /**
             * Format: date-time
             * @description Soft-delete tombstone. Set means deleted; tombstones are included in sync pulls so peers can delete locally.
             */
            deletedAt?: string;
            /**
             * Format: uuid
             * @description Client-supplied UUID.
             */
            id: string;
            isCompleted: boolean;
            /** @description True for recurring payments with no fixed end (e.g. monthly services); requiredCount is ignored and completion is manual. */
            isOpenEnded: boolean;
            name: string;
            /** @enum {string} */
            ownerRaw: "Angel" | "Alejandro";
            /** Format: int64 */
            paidCount: number;
            /** @description CODI QR payload string. */
            qrPayload?: string;
            /** Format: int64 */
            requiredCount: number;
            /**
             * Format: date-time
             * @description Last modification time; drives last-write-wins conflict resolution.
             */
            updatedAt: string;
        };
        ErrorDetail: {
            /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
            location?: string;
            /** @description Error message text */
            message?: string;
            /** @description The value at the given location */
            value?: unknown;
        };
        ErrorModel: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ErrorModel.json
             */
            readonly $schema?: string;
            /**
             * @description A human-readable explanation specific to this occurrence of the problem.
             * @example Property foo is required but is missing.
             */
            detail?: string;
            /** @description Optional list of individual error details */
            errors?: components["schemas"]["ErrorDetail"][] | null;
            /**
             * Format: uri
             * @description A URI reference that identifies the specific occurrence of the problem.
             * @example https://example.com/error-log/abc123
             */
            instance?: string;
            /**
             * Format: int64
             * @description HTTP status code
             * @example 400
             */
            status?: number;
            /**
             * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
             * @example Bad Request
             */
            title?: string;
            /**
             * Format: uri
             * @description A URI reference to human-readable documentation for the error.
             * @default about:blank
             * @example https://example.com/errors/example
             */
            type: string;
        };
        Expense: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Expense.json
             */
            readonly $schema?: string;
            /** @description Monetary amount in MXN with two decimals; handled server-side as exact integer cents. */
            amount: number;
            /** @enum {string} */
            bucketRaw: "shared" | "personal_angel" | "personal_alejandro";
            concept: string;
            /** Format: date-time */
            date: string;
            /**
             * Format: date-time
             * @description Soft-delete tombstone. Set means deleted; tombstones are included in sync pulls so peers can delete locally.
             */
            deletedAt?: string;
            /**
             * Format: uuid
             * @description Client-supplied UUID.
             */
            id: string;
            /** Format: uuid */
            monthId?: string;
            /** @enum {string} */
            payerRaw: "Angel" | "Alejandro";
            /**
             * Format: uuid
             * @description Set when this expense was materialized client-side from an accepted ticket.
             */
            ticketId?: string;
            /**
             * Format: date-time
             * @description Last modification time; drives last-write-wins conflict resolution.
             */
            updatedAt: string;
        };
        LoginInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/LoginInputBody.json
             */
            readonly $schema?: string;
            password: string;
            /** @description One of the two seeded usernames (angel, alejandro). Unknown usernames fail with 401, not validation, to avoid user enumeration semantics in the schema. */
            username: string;
        };
        LoginOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/LoginOutputBody.json
             */
            readonly $schema?: string;
            /** @enum {string} */
            person: "Angel" | "Alejandro";
            /** @description Long-lived opaque bearer token. Valid until revoked. */
            token: string;
        };
        MonthPeriod: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/MonthPeriod.json
             */
            readonly $schema?: string;
            /** @description Monetary amount in MXN with two decimals; handled server-side as exact integer cents. */
            closedSettlementAmount: number;
            /**
             * @description Frozen at close time; null means settled at zero.
             * @enum {string}
             */
            closedSettlementPayerRaw?: "Angel" | "Alejandro";
            /**
             * Format: date-time
             * @description Soft-delete tombstone. Set means deleted; tombstones are included in sync pulls so peers can delete locally.
             */
            deletedAt?: string;
            /**
             * Format: uuid
             * @description Client-supplied UUID.
             */
            id: string;
            isClosed: boolean;
            /** Format: int64 */
            month: number;
            /**
             * Format: date-time
             * @description Last modification time; drives last-write-wins conflict resolution.
             */
            updatedAt: string;
            /** Format: int64 */
            year: number;
        };
        PushOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/PushOutputBody.json
             */
            readonly $schema?: string;
            /**
             * Format: int64
             * @description Number of records applied (new, or newer than the stored version). Stale records are skipped without error.
             */
            accepted: number;
        };
        SyncBatch: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/SyncBatch.json
             */
            readonly $schema?: string;
            deferredPayments?: components["schemas"]["DeferredPaymentItem"][] | null;
            expenses?: components["schemas"]["Expense"][] | null;
            months?: components["schemas"]["MonthPeriod"][] | null;
            tickets?: components["schemas"]["Ticket"][] | null;
            walletMovements?: components["schemas"]["WalletMovement"][] | null;
        };
        Ticket: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Ticket.json
             */
            readonly $schema?: string;
            /**
             * @description Who created the ticket. The creator cannot accept their own ticket; null (legacy) disables that check.
             * @enum {string}
             */
            createdByRaw?: "Angel" | "Alejandro";
            /** Format: date-time */
            date: string;
            /**
             * Format: date-time
             * @description Soft-delete tombstone. Set means deleted; tombstones are included in sync pulls so peers can delete locally.
             */
            deletedAt?: string;
            /**
             * Format: uuid
             * @description Client-supplied UUID.
             */
            id: string;
            /** @description Replaced wholesale on every write; items do not sync independently. */
            items: components["schemas"]["TicketItem"][] | null;
            merchant: string;
            /** Format: uuid */
            monthId?: string;
            /** @description Monetary amount in MXN with two decimals; handled server-side as exact integer cents. */
            paidTotal: number;
            /** @enum {string} */
            payerRaw: "Angel" | "Alejandro";
            reviewNote?: string;
            /** @enum {string} */
            stateRaw: "draft" | "pendingReview" | "accepted";
            /**
             * Format: date-time
             * @description Last modification time; drives last-write-wins conflict resolution.
             */
            updatedAt: string;
        };
        TicketItem: {
            /**
             * @description Null while unassigned.
             * @enum {string}
             */
            bucketRaw?: "shared" | "personal_angel" | "personal_alejandro";
            /**
             * Format: date-time
             * @description Soft-delete tombstone. Set means deleted; tombstones are included in sync pulls so peers can delete locally.
             */
            deletedAt?: string;
            /**
             * Format: uuid
             * @description Client-supplied UUID.
             */
            id: string;
            name: string;
            /** @description Line total (quantity × unit price). */
            price: number;
            /**
             * Format: int64
             * @default 1
             */
            quantity: number;
            /**
             * Format: date-time
             * @description Last modification time; drives last-write-wins conflict resolution.
             */
            updatedAt: string;
        };
        TicketStateInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/TicketStateInputBody.json
             */
            readonly $schema?: string;
            /** @description Attached as the review note when returning to draft. */
            note?: string;
            /** @enum {string} */
            state: "draft" | "pendingReview" | "accepted";
        };
        WalletMovement: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/WalletMovement.json
             */
            readonly $schema?: string;
            /** @description Monetary amount in MXN with two decimals; handled server-side as exact integer cents. */
            amount: number;
            concept: string;
            /** Format: date-time */
            date: string;
            /**
             * Format: date-time
             * @description Soft-delete tombstone. Set means deleted; tombstones are included in sync pulls so peers can delete locally.
             */
            deletedAt?: string;
            /**
             * Format: uuid
             * @description Client-supplied UUID.
             */
            id: string;
            /** @enum {string} */
            personRaw: "Angel" | "Alejandro";
            /** @enum {string} */
            typeRaw: "deposit" | "spend";
            /**
             * Format: date-time
             * @description Last modification time; drives last-write-wins conflict resolution.
             */
            updatedAt: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginOutputBody"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-deferred-payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeferredPaymentItem"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-deferred-payments": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeferredPaymentItem"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "put-deferred-payments": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeferredPaymentItem"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeferredPaymentItem"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "delete-deferred-payments": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-expenses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Expense"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-expenses": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Expense"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "put-expenses": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Expense"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Expense"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "delete-expenses": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-months": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonthPeriod"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-months": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonthPeriod"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "put-months": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MonthPeriod"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonthPeriod"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "delete-months": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "sync-pull": {
        parameters: {
            query: {
                /** @description Return records modified strictly after this instant (RFC 3339). */
                since: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncBatch"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "sync-push": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyncBatch"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PushOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ticket"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-tickets": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ticket"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "put-tickets": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Ticket"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ticket"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "delete-tickets": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "transition-ticket-state": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TicketStateInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ticket"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-wallet-movements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WalletMovement"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-wallet-movements": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WalletMovement"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "put-wallet-movements": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WalletMovement"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WalletMovement"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "delete-wallet-movements": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
}
